### ISSUE TITLE
docker-compose version error

### ISSUE THREAD

**Issue by QGB** [cmdfas/docker-vue-app#1]
```
ERROR: Version in "./docker-compose.yaml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a version of "2" (or "2.0") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/


/docker-vue-app# docker-compose version
docker-compose version 1.8.0, build unknown
docker-py version: 1.9.0
CPython version: 2.7.12
OpenSSL version: OpenSSL 1.0.2g  1 Mar 2016

```

```
version: '3.7'

services: 
  my-app:
    container_name: my-app
    build: 
      context: .
      dockerfile: Dockerfile
    volumes: 
      - '.:/app'
      - '/app/node_modules'
    ports: 
      - '8081:8080'
```
